version: '3'
services:
    redis-master:
        container_name: "redis-master"
        image: redis
        ports:
            - "6379:6379"
        command: "redis-server /etc/redis.conf"
        volumes:
            - "./data/master:/data/"
            - "./master.conf:/etc/redis.conf"