server:
  port: 9080

spring:
  data:
    mongodb:
      uri: mongodb://test:test@localhost:27017/testdb
      username: test
      password: test
      port: 27017
  
logging:
  level:
    root: info