version: "3.2"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
    container_name: "mongodb"
    ports:
      - "27017:27017"

